site:
  title: Trusted Software Factory Documentation
  start_page: tsf::index.adoc
urls:
  latest_version_segment: ''

content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: docs/supplemental-ui

antora:
  extensions:
  - '@antora/lunr-extension'

output:
  dir: build/site
