{{- $host := "" }}
{{- $token := "" }}
{{- $webhookSecret := "" }}
{{- $gitlabSecretObj := (lookup "v1" "Secret" .Values.konflux.tsf.namespace "tsf-gitlab-integration") | default dict -}}
{{- if $gitlabSecretObj }}
  {{- $secretData := required (printf "data not found in secret 'tsf-gitlab-integration' in namespace '%s'" .Values.konflux.tsf.namespace) (get $gitlabSecretObj "data") | default dict -}}
  {{- $host = required (printf "host not found in secret 'tsf-gitlab-integration' in namespace '%s'" .Values.konflux.tsf.namespace) (get $secretData "host") | b64dec | toString -}}
  {{- $token = required (printf "token not found in secret 'tsf-gitlab-integration' in namespace '%s'" .Values.konflux.tsf.namespace) (get $secretData "token") | b64dec | toString -}}
  {{- $webhookSecret = $token -}}
  {{- if hasKey $secretData "webhookSecret" -}}
    {{- $webhookSecret = (get $secretData "webhookSecret") | b64dec | toString -}}
  {{- end -}}
{{- end }}
{{- if (ne $host "") }}
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-as-code-secret
  namespace: default-tenant
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: {{ $host }}
type: kubernetes.io/basic-auth
stringData:
  password: {{ $token | quote }}
  provider.token: {{ $token | quote }}
  webhook.secret: {{ $webhookSecret | quote }}
{{- end }}
