
#
# TPA Integration Secret
#
#   Creates a secret to store integration details.
#
{{- $tpa := .Values.trustedProfileAnalyzer -}}  
{{- $protocol := "https" -}}
{{- if $tpa.openshift.useServiceCa }}
  {{- $protocol = "http" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{
    required ".Values.trustedProfileAnalyzer.integrationSecret.namespace is required"
      $tpa.integrationSecret.namespace
  }}
  name: tsf-trustification-integration
type: Opaque
stringData:
  bombastic_api_url: {{ printf "%s://server%s" $protocol $tpa.appDomain | quote }}
  bombastic_api_service_url: {{ printf "https://server.%s.svc.cluster.local" .Release.Namespace | quote }}
  supported_cyclonedx_version: "{{ $tpa.cycloneDXVersion }}"
